on:
  schedule:
    - cron: 15 15 12 * *
  repository_dispatch:
    types: [check-link]
  workflow_dispatch:

name: Broken Link Check
jobs:
  check:
    name: Broken Link Check
    runs-on: ubuntu-latest
    timeout-minutes: 10
    steps:
      - uses: technote-space/auto-cancel-redundant-job@gh-actions
        with:
          EXCLUDE_MERGED: 'true'
      - name: Broken Link Check
        uses: technote-space/broken-link-checker-action@v2
